### ISSUE TITLE
Feature request: Alternative shortcut for ESC

### ISSUE THREAD

**Issue by pklaschka** [nimblenote/nimblenote#2]
First of all: Thank you for this great app. I've been on a long search for a simple, quick note-taking app, and I believe my search has just come to an end.

One minor request I have would be to provide some alternative shortcut (in addition to it, without replacing it) to the <kbd>ESC</kbd> (as reaching for the key removes me "from the zone," so to speak, by reaching for the "far away" key, which, in every other aspect, this app manages well with its keyboard-centric approach).

Coming from vim, <kbd>Ctrl</kbd>+<kbd>[</kbd> (and its international alternatives, e.g., <kbd>Ctrl</kbd>+<kbd>ü</kbd> on German keyboard layouts) may be an option. In truth, though, any shortcut that's possible to reach without completely leaving the keyboard's home row works.

Thanks again for the great app (this really is only a minor detail for me that could make an outstanding app even better)  🙂

**Comment by davidwinter** [comment]
Thanks, @pklaschka for reaching out and for the kind words! I'll keep this in mind for a future feature :+1: 

One thing I've done personally, is to remap my <kbd>CAPS</kbd> key to <kbd>ESC</kbd>, as I rarely use that key, and that then means you have something like <kbd>ESC</kbd> but on the home row. Would highly recommend it.
