### ISSUE TITLE
Display help when or welcome text when no note is selected

### ISSUE THREAD

**Issue by bubonicfred** [nimblenote/nimblenote#3]
I sent you an email a bit ago, but filing an issue to make sure :)
When no note is selected nothing is displayed in the note section, this should display the help or welcome text, especially in the absense of menus.
This would be especially helpful as the website does not currently list the help or delete commands.

**Comment by davidwinter** [comment]
Thanks, @bubonicfred for suggesting this - I've not been receiving certain emails or notifications on GitHub, so I do apologise for not replying!!

This is a really good idea, and I've added it to my list of things to implement :+1:

**Comment by davidwinter** [comment]
@bubonicfred I've now added a message when no note is selected which has basic usage of nimblenote, but also, how to open the help text for more information. You should see this change after nimblenote has upgraded to v3.1.0.
