### ISSUE TITLE
Some concerns

### ISSUE THREAD

**Issue by jojoharry16** [nimblenote/nimblenote#4]
# Foreward
Love the simplicity and speed of this app
# Issues
It installed on my C: drive without admin privileges or confirmation? 
Where's the code?
I also can't delete notes
# Actions
I moved the program manually to another drive and it seems to be working as intended, just weird there's no option from the installer.
# Conclusion
I still love the application, just have the above concerns :) If you publish the code more people can hop on and add in the features themselves

**Comment by davidwinter** [comment]
@jojoharry16 glad that you're enjoying the app! We use a tool called `electron-builder` to handle the creation of the installer, so we're just using the defaults for this. Was there any particular functionality you were seeking when installing `nimblenote`?

To delete notes, with a note selected, you should be able to use the keyboard shortcut <kbd>CTRL</kbd> + <kbd>D</kbd>, which will then prompt you to confirm deletion.
