### ISSUE TITLE
The road to open source

### ISSUE THREAD

**Issue by almereyda** [nimblenote/nimblenote#5]
As a member and user of the FLOSS community, I would like to see the open sourcing of `nimblenote` take place as intended, to be able to profit from the network effects for collaboration and support of the application that this process allows.

What can we as a member of the user community of `nimblenote` help out with to see this plan succeed as laid out before?

**Comment by davidwinter** [comment]
Thanks, @almereyda for the enthusiasm - I'm keen to open source this too. As it was first developed as a prototype, I'm currently tidying up the code into something I'm happier about sharing with the community. Until it's at that place, I'm afraid we'll have to hold tight.
