### ISSUE TITLE
Add Open Note in External Editor

### ISSUE THREAD

**Issue by leejoramo-d51** [nimblenote/nimblenote#6]
As a long time nvAlt user, I really like nimblenote. I have often looked for an alternative when working on Windows, Very happy to finally find what I want with a clean and focused design.

While I could ask for a variety of nvAlt features to be added in nimblenote, the biggest request I have is to allow me to open the current note in an external editor. 

This would allow for using all of the power of your preferred editor with all of your preferred keybindings and tools and extensions. For most simple notes, nimblenote is fine. But if you need more formatting features such as tables, footnotes, code fences, or tools such as spelling checkers, todo managers,  it would be great to have an easy way to jump into an external editor.

**Comment by davidwinter** [comment]
Thanks, @leejoramo-d51 - I've added this to nimblenote's wishlist :+1:
